services:
  sense_face_verification:
    container_name: sense_face_verification_container
    build:
      context: .
      dockerfile: Dockerfile
    image: sense_face_verification_image
    ports:
      - "3015:3015"  # map host:container
    volumes:
      - ./uploads:/app/uploads
      - ./temp_files:/app/temp_files
    restart: unless-stopped
    environment:
      - TZ=Asia/Kolkata
